openapi: 3.1.0
info:
  title: Taxicode Booking API
  version: 1.3.0
  description: |
    Taxicode booking and payment APIs.  
    All endpoints return HTTP 200; check `"status"` in JSON for errors.

servers:
  - url: https://api.taxicode.com

paths:
  /booking/quote/:
    post:
      operationId: createBookingQuote
      summary: Get a quote for a journey (or a business-level error)
      description: |
        Request a journey quote.  
        Send `date` as `"asap"` or a UNIX timestamp (timestamps within 1 hour => ASAP).
        Always HTTP 200: check `status` in JSON.
      parameters:
        - in: query
          name: key
          schema:
            type: string
          required: true
          description: Your API key (can also be sent in JSON body)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteRequest'
            examples:
              asapExample:
                value:
                  key: "YOUR_API_KEY"
                  pickup: "51.5074,-0.1278"
                  destination: "51.5098,-0.1180"
                  date: "asap"
                  people: 2
                  quote_type: mileage
              scheduledExample:
                value:
                  key: "YOUR_API_KEY"
                  pickup: "51.5074,-0.1278"
                  destination: "51.5098,-0.1180"
                  date: 1710150000
                  people: 2
                  quote_type: mileage
      responses:
        '200':
          description: Quote or business-level error response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/QuoteResponse'
                  - $ref: '#/components/schemas/BusinessError'
              examples:
                successExample:
                  summary: Valid quote result
                  value:
                    status: "OK"
                    journey_id: "CA765D41B18AFE79C1A1796A7F8557A4"
                    journey:
                      pickup:
                        string: "york"
                        position: [53.957744, -1.082259]
                        postcode: "YO1 9NF"
                      vias: []
                      destination:
                        string: "york station"
                        position: [53.958107, -1.092385]
                        postcode: "YO24"
                      distance: 1
                      duration: 238
                      duration_text: "3 mins"
                      date: "2024-07-30 12:00:00"
                      return: false
                      people: 1
                      quote_type: "mileage"
                      hourly: false
                      is_airport: false
                    quotes:
                      83EEECC21BBC13268C67526D08B58160:
                        $ref: "#/components/schemas/Quote"
                    card:
                      - code: "VISA"
                        name: "Visa Credit"
                        uplift: 5
                    payment_url: "https://secure.taxicode.com/api/"
                    continue_url: "https://secure.taxicode.com/payment/"
                    secureType: "secure.taxicode.com"
                    api_checkout_url: "https://api.taxicode.com/secure/checkout_session/create/"
                errorDatePast:
                  summary: Past date error
                  value:
                    status: "ERROR"
                    error: "Sorry, journey date and time in the past are not valid"
                errorMissingFields:
                  summary: Missing fields error
                  value:
                    status: "ERROR"
                    error: "Pickup and Destination must be set."
                errorGeneric:
                  summary: Generic error
                  value:
                    status: "ERROR"
                    error: "Sorry, generic error message"

  /booking/pay/:
    post:
      operationId: createBookingPayment
      summary: Confirm booking and initiate payment
      description: |
        Finalize the booking using a selected quote/vehicle.  
        Returns a `session.api_checkout_url` to complete payment.  
        Always HTTP 200: check `status` in JSON.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingPaymentRequest'
      responses:
        '200':
          description: Booking payment result
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BookingPaymentSuccess'
                  - $ref: '#/components/schemas/BusinessError'
              examples:
                success:
                  summary: Booking payment initiated
                  value:
                    status: "OK"
                    session:
                      state_hash: "abc123"
                      gateway_public_key: "xyz456"
                      booking_ref: "REF123456"
                      api_checkout_url: "https://secure.taxicode.com/payment/?session=xyz"
                errorQuote:
                  summary: Quote not found or invalid
                  value:
                    status: "ERROR"
                    error: "Quote not found"
